name: Push

on:
  push:
  workflow_dispatch:

jobs:
  push:
    name: Push

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          pip install -r requirements.txt
          python redroid.py -m
          docker image tag redroid/redroid:11.0.0_magisk catlair/redroid:11.0.0_magisk
          docker push catlair/redroid:11.0.0_magisk_fix
